# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a40bf47b9bb0be4ae97fd0d1b86763fb8e4799cb40c657e72ed69c05566a4ffdf2930806902d21d202111724ba2b032942b985535814237e4b8b68acc9e337be

test:
  secret_key_base: 5d86e70356c5b6c8ccfee6a1e9cc40d0b0af7918ed73fbd3daf0800b82cc0057d9a1502446fbe3b594d22f3558bda4fa113e1c296510a7eaf79cdb6b87594d43

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
